import { Category, Prisma, PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const generateUsers = async () => {
  const users = [
    {
      email: 'pmuckloe0@adobe.com',
      password: '11111111',
      name: 'Philippine Muckloe',
    },
    {
      email: 'shighway1@people.com.cn',
      password: '22222222',
      name: 'Suzette Highway',
    },
    {
      email: 'lbroek2@hibu.com',
      password: '33333333',
      name: 'Lilli Broek',
    },
  ].map((item) => {
    const passwordHash = bcrypt.hashSync(item.password, 10);

    return {
      email: item.email,
      name: item.name,
      passwordHash,
    };
  });

  await prisma.user.createMany({
    data: users,
  });
};

const generateCategories = async () => {
  const firstUserCategories: Prisma.CategoryCreateManyInput[] = [
    { name: 'Salary', color: '#D20103', type: 'INCOME', userId: 1 },
    { name: 'Rental Income', color: '#FE9900', type: 'INCOME', userId: 1 },
    { name: 'Gifts', color: '#FFDE59', type: 'INCOME', userId: 1 },

    { name: 'Groceries', color: '#7DDA58', type: 'EXPENSE', userId: 1 },
    { name: 'Rent', color: '#5DE2E7', type: 'EXPENSE', userId: 1 },
    { name: 'Transportation', color: '#060270', type: 'EXPENSE', userId: 1 },
    { name: 'Fitness', color: '#CC6CE7', type: 'EXPENSE', userId: 1 },
  ];

  const secondUserCategories: Prisma.CategoryCreateManyInput[] = [
    { name: 'Salary', color: '#7DDA58', type: 'INCOME', userId: 2 },

    { name: 'Groceries', color: '#FFECA1', type: 'EXPENSE', userId: 2 },
    { name: 'Housing', color: '#FE9900', type: 'EXPENSE', userId: 2 },
    { name: 'Transportation', color: '#FE9900', type: 'EXPENSE', userId: 2 },
    { name: 'Healthcare', color: '#EFC3CA', type: 'EXPENSE', userId: 2 },
  ];

  await prisma.category.createMany({
    data: [...firstUserCategories, ...secondUserCategories],
  });
};

const generateTransactions = async () => {
  const firstUserIncomes = [
    {
      name: 'suscipit ligula in lacus curabitur',
      amount: 1423.56,
      notes: null,
      createdAt: '2024-03-18T09:52:01Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'vulputate vitae nisl',
      amount: 1644.17,
      notes: null,
      createdAt: '2024-06-08T07:06:21Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'tempus sit amet',
      amount: 1089.55,
      notes:
        'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
      createdAt: '2023-12-30T21:06:30Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'aenean lectus pellentesque',
      amount: 1294.72,
      notes: null,
      createdAt: '2023-12-01T03:13:10Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'at vulputate',
      amount: 1125.43,
      notes:
        'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.',
      createdAt: '2024-04-05T20:15:35Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'magna bibendum imperdiet nullam',
      amount: 1030.29,
      notes: null,
      createdAt: '2025-01-16T05:54:54Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'nulla integer',
      amount: 963.99,
      notes: null,
      createdAt: '2024-07-18T13:31:28Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'laoreet ut rhoncus aliquet pulvinar',
      amount: 1885.25,
      notes: null,
      createdAt: '2023-05-30T03:30:12Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'nascetur ridiculus mus etiam',
      amount: 1117.4,
      notes: null,
      createdAt: '2024-07-18T23:28:10Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'hac habitasse',
      amount: 853.33,
      notes: null,
      createdAt: '2024-09-15T02:13:39Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'tortor risus dapibus augue',
      amount: 944.05,
      notes: null,
      createdAt: '2024-07-25T14:53:58Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'vitae mattis nibh ligula',
      amount: 1488.28,
      notes: null,
      createdAt: '2023-03-21T11:37:04Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'sed tincidunt',
      amount: 1633.66,
      notes:
        'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.',
      createdAt: '2023-06-01T11:17:17Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'ac neque',
      amount: 1870.46,
      notes: null,
      createdAt: '2024-01-12T11:06:43Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'nulla ut erat id',
      amount: 1776.84,
      notes: null,
      createdAt: '2024-09-26T20:51:34Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'vulputate elementum nullam',
      amount: 1263.0,
      notes: null,
      createdAt: '2023-12-03T01:09:37Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'est risus',
      amount: 997.32,
      notes: null,
      createdAt: '2023-11-22T17:00:47Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'ante ipsum primis',
      amount: 1648.92,
      notes: null,
      createdAt: '2023-12-09T21:11:22Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'diam neque vestibulum eget',
      amount: 1854.74,
      notes: null,
      createdAt: '2023-03-21T05:09:08Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'pellentesque eget nunc donec',
      amount: 1361.97,
      notes:
        'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.',
      createdAt: '2025-01-27T09:57:06Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'diam id ornare',
      amount: 821.87,
      notes: null,
      createdAt: '2023-07-08T18:22:12Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'id pretium iaculis diam erat',
      amount: 1519.02,
      notes: 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
      createdAt: '2024-02-14T19:14:27Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'ipsum dolor sit amet consectetuer',
      amount: 577.66,
      notes: 'Quisque ut erat. Curabitur gravida nisi at nibh.',
      createdAt: '2024-03-04T16:26:09Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'suscipit nulla elit ac nulla',
      amount: 1835.1,
      notes:
        'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
      createdAt: '2024-02-06T10:45:24Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'convallis duis consequat',
      amount: 731.3,
      notes: null,
      createdAt: '2024-05-16T10:30:04Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'hac habitasse platea dictumst maecenas',
      amount: 1215.44,
      notes: null,
      createdAt: '2023-03-02T14:46:31Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'ante ipsum',
      amount: 1524.39,
      notes:
        'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
      createdAt: '2023-06-16T00:08:19Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'luctus nec molestie sed justo',
      amount: 1012.13,
      notes:
        'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.',
      createdAt: '2023-04-13T22:44:55Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'blandit lacinia',
      amount: 1337.36,
      notes: null,
      createdAt: '2024-05-20T14:56:38Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'in est risus auctor sed',
      amount: 1617.02,
      notes:
        'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',
      createdAt: '2024-03-11T08:26:16Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'integer tincidunt ante vel',
      amount: 1894.76,
      notes: null,
      createdAt: '2024-12-15T00:13:21Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'dolor sit amet',
      amount: 1095.91,
      notes:
        'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
      createdAt: '2023-08-19T21:09:33Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'nisl venenatis',
      amount: 652.03,
      notes: null,
      createdAt: '2024-12-28T10:21:15Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'iaculis justo in',
      amount: 1650.69,
      notes: null,
      createdAt: '2024-07-08T20:38:44Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'in magna',
      amount: 1230.2,
      notes: null,
      createdAt: '2023-05-31T07:31:57Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'eu felis fusce posuere felis',
      amount: 1233.68,
      notes: null,
      createdAt: '2024-10-09T00:01:42Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'sapien arcu sed augue',
      amount: 1897.69,
      notes: null,
      createdAt: '2024-09-10T02:13:04Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'lacinia nisi venenatis',
      amount: 1532.89,
      notes: null,
      createdAt: '2024-01-12T06:54:42Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'donec posuere metus',
      amount: 1800.34,
      notes: null,
      createdAt: '2024-11-20T22:48:15Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'ante vivamus tortor duis mattis',
      amount: 1966.55,
      notes:
        'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.',
      createdAt: '2024-07-22T02:45:26Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'ultrices posuere',
      amount: 1456.05,
      notes: null,
      createdAt: '2024-07-10T02:17:46Z',
      categoryId: 1,
      userId: 1,
    },
    {
      name: 'vivamus vel nulla',
      amount: 706.9,
      notes: null,
      createdAt: '2024-11-01T02:30:59Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'mauris sit amet eros',
      amount: 1281.57,
      notes: null,
      createdAt: '2023-12-24T06:48:12Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'libero convallis',
      amount: 1400.28,
      notes:
        'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
      createdAt: '2023-05-31T12:51:04Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'id luctus nec',
      amount: 1015.13,
      notes: null,
      createdAt: '2023-04-09T18:25:56Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'ut suscipit a feugiat et',
      amount: 581.98,
      notes:
        'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.',
      createdAt: '2023-06-26T10:19:09Z',
      categoryId: 2,
      userId: 1,
    },
    {
      name: 'aliquet massa id',
      amount: 1695.14,
      notes:
        'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.',
      createdAt: '2024-10-09T11:17:42Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'consequat morbi a ipsum integer',
      amount: 913.11,
      notes: null,
      createdAt: '2023-10-15T02:39:11Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'eget orci vehicula',
      amount: 1438.05,
      notes: null,
      createdAt: '2023-06-22T20:48:16Z',
      categoryId: 3,
      userId: 1,
    },
    {
      name: 'pretium iaculis justo in',
      amount: 1798.52,
      notes: null,
      createdAt: '2023-12-15T10:14:50Z',
      categoryId: 2,
      userId: 1,
    },
  ];
  const firstUserExpenses = [
    {
      name: 'id lobortis convallis',
      amount: 25.26,
      notes: null,
      createdAt: '2024-11-02T19:46:38Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'nam dui',
      amount: 125.19,
      notes: null,
      createdAt: '2024-05-24T18:57:01Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'fusce consequat nulla nisl',
      amount: 261.61,
      notes: null,
      createdAt: '2025-01-06T12:44:42Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'odio consequat varius',
      amount: 495.3,
      notes: null,
      createdAt: '2023-03-09T13:04:48Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'ornare consequat lectus',
      amount: 41.28,
      notes: null,
      createdAt: '2023-09-04T04:45:29Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'at nulla suspendisse potenti',
      amount: 251.2,
      notes:
        'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.',
      createdAt: '2023-03-11T07:03:59Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'a nibh in quis justo',
      amount: 129.77,
      notes: null,
      createdAt: '2024-01-12T21:56:43Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'mattis nibh ligula nec',
      amount: 233.97,
      notes: null,
      createdAt: '2023-06-16T00:30:36Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'rhoncus mauris enim',
      amount: 316.75,
      notes:
        'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.',
      createdAt: '2024-12-06T09:22:12Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'id nulla ultrices',
      amount: 310.3,
      notes: 'Pellentesque ultrices mattis odio.',
      createdAt: '2023-03-02T07:24:53Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'augue vestibulum rutrum rutrum neque',
      amount: 433.05,
      notes: 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.',
      createdAt: '2024-07-25T15:08:31Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'lacinia sapien',
      amount: 254.4,
      notes: null,
      createdAt: '2023-03-28T16:07:54Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'adipiscing elit proin risus praesent',
      amount: 369.8,
      notes: null,
      createdAt: '2023-02-24T00:05:13Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'elementum ligula',
      amount: 269.4,
      notes:
        'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',
      createdAt: '2023-10-25T01:13:49Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'semper est quam',
      amount: 113.92,
      notes:
        'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
      createdAt: '2023-03-06T03:56:11Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'laoreet ut',
      amount: 429.77,
      notes: null,
      createdAt: '2023-08-02T19:13:01Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'vel nisl',
      amount: 489.08,
      notes:
        'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
      createdAt: '2024-06-26T01:20:14Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'pellentesque ultrices',
      amount: 303.29,
      notes: null,
      createdAt: '2024-12-14T00:38:46Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'nisi at nibh in hac',
      amount: 76.89,
      notes: null,
      createdAt: '2024-09-15T03:40:25Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'ut blandit',
      amount: 409.12,
      notes:
        'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.',
      createdAt: '2024-12-22T00:29:53Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'convallis nulla neque libero convallis',
      amount: 165.89,
      notes: null,
      createdAt: '2024-10-11T07:01:39Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'mauris lacinia sapien quis libero',
      amount: 307.64,
      notes: null,
      createdAt: '2023-11-24T02:33:58Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'cum sociis natoque penatibus',
      amount: 272.78,
      notes:
        'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',
      createdAt: '2023-04-09T18:21:46Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'praesent lectus vestibulum quam sapien',
      amount: 334.55,
      notes:
        'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',
      createdAt: '2024-07-16T18:48:19Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'ante ipsum primis',
      amount: 380.52,
      notes: null,
      createdAt: '2024-07-25T22:11:17Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'pretium quis',
      amount: 20.46,
      notes: 'Curabitur in libero ut massa volutpat convallis.',
      createdAt: '2025-02-04T06:55:52Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'justo sollicitudin ut suscipit',
      amount: 198.48,
      notes: null,
      createdAt: '2023-12-22T15:03:50Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'curabitur in libero',
      amount: 235.36,
      notes: null,
      createdAt: '2024-01-16T02:39:45Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'in tempor turpis nec',
      amount: 169.24,
      notes: 'Morbi a ipsum. Integer a nibh. In quis justo.',
      createdAt: '2024-02-29T23:18:22Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'sed justo pellentesque viverra pede',
      amount: 250.41,
      notes: null,
      createdAt: '2024-06-21T02:12:57Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'morbi vel lectus',
      amount: 100.79,
      notes: null,
      createdAt: '2023-05-07T16:11:47Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'lacus morbi sem mauris laoreet',
      amount: 56.05,
      notes: null,
      createdAt: '2023-04-24T10:56:17Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'dapibus at diam nam',
      amount: 482.23,
      notes: null,
      createdAt: '2024-10-02T02:04:02Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'eget tempus vel',
      amount: 226.83,
      notes: null,
      createdAt: '2024-09-30T11:59:42Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'sed interdum venenatis turpis enim',
      amount: 285.44,
      notes: null,
      createdAt: '2024-09-30T17:55:47Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'mi pede',
      amount: 468.07,
      notes: null,
      createdAt: '2024-07-13T14:44:38Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'elementum pellentesque quisque porta',
      amount: 208.77,
      notes: null,
      createdAt: '2023-04-08T10:03:24Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'nulla suscipit ligula in',
      amount: 251.84,
      notes: null,
      createdAt: '2025-01-05T07:06:36Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'ac diam cras',
      amount: 335.87,
      notes: null,
      createdAt: '2024-01-26T22:01:47Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'ipsum primis',
      amount: 301.34,
      notes: null,
      createdAt: '2023-03-08T16:57:07Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'nonummy integer non',
      amount: 223.09,
      notes:
        'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.',
      createdAt: '2024-08-25T04:28:12Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'mollis molestie lorem quisque',
      amount: 469.52,
      notes:
        'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',
      createdAt: '2024-06-19T01:49:17Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'mauris eget massa tempor convallis',
      amount: 226.69,
      notes: null,
      createdAt: '2024-04-02T09:43:21Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'rutrum at lorem integer',
      amount: 67.24,
      notes: null,
      createdAt: '2025-02-07T20:21:33Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'nisl duis bibendum felis',
      amount: 157.75,
      notes: null,
      createdAt: '2023-02-24T14:14:36Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'a nibh in quis justo',
      amount: 406.35,
      notes: 'Morbi ut odio.',
      createdAt: '2024-10-21T05:52:22Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'nulla nisl',
      amount: 212.59,
      notes: null,
      createdAt: '2023-05-10T21:14:23Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'nec dui luctus rutrum nulla',
      amount: 411.53,
      notes:
        'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',
      createdAt: '2025-01-05T16:01:35Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'in hac habitasse platea dictumst',
      amount: 454.73,
      notes:
        'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.',
      createdAt: '2024-09-19T16:35:33Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'nunc rhoncus',
      amount: 133.53,
      notes: null,
      createdAt: '2024-08-08T17:02:29Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'duis faucibus',
      amount: 279.01,
      notes: null,
      createdAt: '2024-06-10T01:45:24Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'id massa id',
      amount: 416.75,
      notes:
        'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
      createdAt: '2024-02-18T13:56:15Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'ante vel ipsum praesent blandit',
      amount: 51.57,
      notes:
        'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.',
      createdAt: '2023-08-16T23:10:47Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'adipiscing elit proin',
      amount: 497.93,
      notes: null,
      createdAt: '2023-11-14T21:29:16Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'eu felis fusce',
      amount: 429.02,
      notes:
        'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',
      createdAt: '2024-02-12T08:40:13Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'volutpat quam',
      amount: 219.47,
      notes:
        'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.',
      createdAt: '2023-08-13T04:05:44Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'maecenas ut massa',
      amount: 199.87,
      notes: null,
      createdAt: '2023-05-09T16:02:50Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'cursus vestibulum proin',
      amount: 183.97,
      notes: null,
      createdAt: '2023-11-09T07:27:59Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'cum sociis natoque penatibus',
      amount: 112.17,
      notes: null,
      createdAt: '2023-05-31T00:36:39Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'tortor risus dapibus augue',
      amount: 206.95,
      notes: 'Aliquam non mauris.',
      createdAt: '2023-06-06T16:24:23Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'amet nulla',
      amount: 467.61,
      notes: null,
      createdAt: '2023-10-05T05:18:38Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'tincidunt eget tempus vel pede',
      amount: 232.91,
      notes: null,
      createdAt: '2024-01-19T09:33:10Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'felis fusce posuere',
      amount: 493.38,
      notes: null,
      createdAt: '2024-04-03T14:58:15Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'vel sem',
      amount: 147.61,
      notes: null,
      createdAt: '2023-09-14T17:43:03Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'turpis nec euismod scelerisque',
      amount: 26.16,
      notes: null,
      createdAt: '2023-09-26T03:50:23Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'id massa id',
      amount: 289.17,
      notes: null,
      createdAt: '2025-02-01T20:56:08Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'sed vel enim sit',
      amount: 46.91,
      notes: null,
      createdAt: '2024-10-10T22:44:47Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'quam pede lobortis',
      amount: 76.83,
      notes: null,
      createdAt: '2023-04-16T16:11:09Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'faucibus accumsan odio',
      amount: 119.62,
      notes: null,
      createdAt: '2024-12-10T10:46:32Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'proin leo odio',
      amount: 150.3,
      notes: 'In congue.',
      createdAt: '2024-02-24T14:53:29Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'pede morbi',
      amount: 235.77,
      notes: null,
      createdAt: '2023-03-09T01:02:31Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'quam suspendisse potenti',
      amount: 490.19,
      notes: 'Quisque ut erat.',
      createdAt: '2024-07-30T06:35:00Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'nunc nisl duis bibendum felis',
      amount: 71.57,
      notes: null,
      createdAt: '2024-03-06T01:57:57Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'quis turpis eget',
      amount: 246.21,
      notes: null,
      createdAt: '2024-04-30T09:49:40Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'consequat ut nulla sed',
      amount: 39.96,
      notes:
        'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.',
      createdAt: '2023-04-19T20:43:14Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'etiam justo etiam pretium iaculis',
      amount: 42.59,
      notes:
        'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.',
      createdAt: '2024-12-08T21:25:55Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'eget elit sodales',
      amount: 312.84,
      notes: null,
      createdAt: '2024-10-24T17:41:21Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'ipsum aliquam non',
      amount: 350.06,
      notes: null,
      createdAt: '2024-06-26T07:58:17Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'curae donec pharetra magna vestibulum',
      amount: 107.53,
      notes: null,
      createdAt: '2024-01-23T08:24:45Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'phasellus sit amet',
      amount: 385.57,
      notes: null,
      createdAt: '2023-12-26T17:18:33Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'eu interdum eu',
      amount: 113.7,
      notes: null,
      createdAt: '2025-02-01T16:09:39Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'gravida nisi',
      amount: 401.64,
      notes:
        'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.',
      createdAt: '2024-10-29T10:37:52Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'pharetra magna',
      amount: 31.16,
      notes: null,
      createdAt: '2024-06-13T20:27:18Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'platea dictumst morbi vestibulum',
      amount: 442.81,
      notes:
        'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.',
      createdAt: '2023-11-30T08:36:29Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'purus phasellus in felis',
      amount: 246.56,
      notes: null,
      createdAt: '2023-11-24T03:41:59Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'rutrum nulla nunc purus phasellus',
      amount: 69.05,
      notes: null,
      createdAt: '2024-06-23T23:32:39Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'sed lacus morbi sem mauris',
      amount: 497.91,
      notes:
        'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.',
      createdAt: '2023-11-04T21:49:56Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'placerat praesent',
      amount: 145.05,
      notes:
        'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',
      createdAt: '2023-11-13T21:38:47Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'etiam vel augue vestibulum',
      amount: 61.83,
      notes: null,
      createdAt: '2024-03-03T05:08:56Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'ut suscipit a feugiat et',
      amount: 243.38,
      notes: null,
      createdAt: '2023-05-27T03:24:08Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'sapien iaculis congue vivamus',
      amount: 265.61,
      notes: null,
      createdAt: '2024-04-08T14:17:28Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'nam tristique tortor',
      amount: 379.74,
      notes: null,
      createdAt: '2024-01-18T10:14:46Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'condimentum curabitur in libero',
      amount: 128.89,
      notes:
        'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.',
      createdAt: '2023-10-11T18:33:51Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'nam congue risus semper porta',
      amount: 447.68,
      notes: null,
      createdAt: '2024-10-03T02:41:40Z',
      categoryId: 4,
      userId: 1,
    },
    {
      name: 'orci pede venenatis',
      amount: 369.82,
      notes:
        'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
      createdAt: '2024-08-08T08:31:11Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'curabitur in',
      amount: 450.57,
      notes:
        'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.',
      createdAt: '2024-04-02T17:34:25Z',
      categoryId: 5,
      userId: 1,
    },
    {
      name: 'platea dictumst aliquam augue',
      amount: 53.92,
      notes: 'Nulla ut erat id mauris vulputate elementum. Nullam varius.',
      createdAt: '2023-11-19T22:24:51Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'non interdum in',
      amount: 58.1,
      notes: null,
      createdAt: '2024-06-27T21:03:48Z',
      categoryId: 6,
      userId: 1,
    },
    {
      name: 'proin risus praesent lectus vestibulum',
      amount: 404.07,
      notes:
        'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
      createdAt: '2025-02-03T23:15:10Z',
      categoryId: 7,
      userId: 1,
    },
    {
      name: 'ac enim in tempor',
      amount: 234.69,
      notes: null,
      createdAt: '2024-12-01T12:31:51Z',
      categoryId: 5,
      userId: 1,
    },
  ];
  const secondUserIncomes = [
    {
      name: 'magnis dis parturient montes',
      amount: 1663.94,
      notes: null,
      createdAt: '2023-04-11T19:17:38Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'quis turpis eget elit sodales',
      amount: 1310.57,
      notes: null,
      createdAt: '2024-12-02T11:03:25Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'dolor vel est donec odio',
      amount: 728.31,
      notes: null,
      createdAt: '2023-03-31T17:21:50Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'luctus et ultrices posuere',
      amount: 2276.2,
      notes: null,
      createdAt: '2024-02-11T01:26:50Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'amet nunc',
      amount: 1695.63,
      notes:
        'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',
      createdAt: '2023-03-24T02:09:21Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'imperdiet sapien urna pretium nisl',
      amount: 1231.8,
      notes: null,
      createdAt: '2024-10-22T22:55:36Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'enim lorem ipsum',
      amount: 1026.12,
      notes:
        'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
      createdAt: '2024-06-15T23:50:42Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'praesent blandit nam nulla integer',
      amount: 1914.38,
      notes:
        'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
      createdAt: '2025-01-19T03:11:19Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'facilisi cras non velit nec',
      amount: 944.79,
      notes:
        'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.',
      createdAt: '2024-03-08T20:06:21Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'aliquam non mauris',
      amount: 1066.94,
      notes: null,
      createdAt: '2024-05-06T02:41:52Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'facilisi cras non velit',
      amount: 2036.66,
      notes: null,
      createdAt: '2024-11-28T12:05:38Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'ipsum primis in faucibus orci',
      amount: 2847.27,
      notes: null,
      createdAt: '2024-06-28T08:21:05Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'mattis pulvinar nulla pede ullamcorper',
      amount: 700.61,
      notes:
        'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.',
      createdAt: '2023-05-20T04:15:45Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'justo aliquam quis turpis eget',
      amount: 2551.88,
      notes: null,
      createdAt: '2023-12-12T22:43:48Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'turpis nec euismod',
      amount: 1018.82,
      notes: null,
      createdAt: '2025-01-19T12:13:19Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'vel augue vestibulum ante',
      amount: 1810.59,
      notes: null,
      createdAt: '2024-02-25T08:21:22Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'nulla tellus in',
      amount: 2654.03,
      notes: null,
      createdAt: '2023-04-15T13:35:05Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'auctor sed tristique in',
      amount: 1121.56,
      notes: null,
      createdAt: '2023-07-20T07:51:31Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'aliquam lacus',
      amount: 2916.37,
      notes: 'Integer ac neque. Duis bibendum.',
      createdAt: '2024-09-02T00:18:40Z',
      categoryId: 8,
      userId: 2,
    },
    {
      name: 'pede libero',
      amount: 902.68,
      notes: null,
      createdAt: '2024-10-12T23:24:56Z',
      categoryId: 8,
      userId: 2,
    },
  ];
  const secondUserExpenses = [
    {
      name: 'montes nascetur ridiculus mus vivamus',
      amount: 95.95,
      notes: null,
      createdAt: '2024-12-23T00:09:16Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'scelerisque quam turpis adipiscing',
      amount: 85.08,
      notes: null,
      createdAt: '2024-12-16T10:08:43Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'tincidunt lacus at velit',
      amount: 172.24,
      notes: null,
      createdAt: '2023-03-18T08:11:17Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'habitasse platea dictumst',
      amount: 93.14,
      notes: null,
      createdAt: '2024-04-21T00:20:37Z',
      categoryId: 9,
      userId: 2,
    },
    {
      name: 'luctus et ultrices',
      amount: 31.46,
      notes: null,
      createdAt: '2023-05-03T19:45:44Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'ante vestibulum ante',
      amount: 74.84,
      notes: null,
      createdAt: '2023-10-19T21:01:56Z',
      categoryId: 10,
      userId: 2,
    },
    {
      name: 'velit donec diam',
      amount: 134.87,
      notes:
        'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
      createdAt: '2023-11-25T12:02:37Z',
      categoryId: 12,
      userId: 2,
    },
    {
      name: 'congue risus semper porta',
      amount: 29.72,
      notes: null,
      createdAt: '2023-06-28T12:53:03Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'ut blandit non interdum in',
      amount: 56.41,
      notes: null,
      createdAt: '2023-05-10T09:22:43Z',
      categoryId: 10,
      userId: 2,
    },
    {
      name: 'quam pede',
      amount: 178.96,
      notes: null,
      createdAt: '2024-03-29T22:25:00Z',
      categoryId: 9,
      userId: 2,
    },
    {
      name: 'felis ut at dolor',
      amount: 43.14,
      notes: null,
      createdAt: '2023-05-26T04:30:37Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'quis odio',
      amount: 54.69,
      notes:
        'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.',
      createdAt: '2024-06-26T10:42:47Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'tempus semper est',
      amount: 11.34,
      notes: null,
      createdAt: '2023-04-19T02:33:06Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'vestibulum rutrum',
      amount: 15.45,
      notes: null,
      createdAt: '2023-03-30T08:25:04Z',
      categoryId: 10,
      userId: 2,
    },
    {
      name: 'mus etiam vel augue vestibulum',
      amount: 101.3,
      notes:
        'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.',
      createdAt: '2025-01-26T18:01:39Z',
      categoryId: 9,
      userId: 2,
    },
    {
      name: 'pede ullamcorper augue',
      amount: 71.64,
      notes:
        'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
      createdAt: '2024-09-29T22:07:06Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'justo pellentesque viverra',
      amount: 177.47,
      notes:
        'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.',
      createdAt: '2024-01-27T17:03:27Z',
      categoryId: 10,
      userId: 2,
    },
    {
      name: 'tincidunt ante vel ipsum praesent',
      amount: 26.63,
      notes: null,
      createdAt: '2024-11-13T13:35:43Z',
      categoryId: 10,
      userId: 2,
    },
    {
      name: 'cursus vestibulum',
      amount: 57.18,
      notes: 'Nullam sit amet turpis elementum ligula vehicula consequat.',
      createdAt: '2023-07-09T09:15:02Z',
      categoryId: 10,
      userId: 2,
    },
    {
      name: 'mollis molestie lorem',
      amount: 130.25,
      notes: null,
      createdAt: '2024-09-09T16:45:09Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'in sagittis',
      amount: 45.53,
      notes: null,
      createdAt: '2024-04-25T00:50:44Z',
      categoryId: 12,
      userId: 2,
    },
    {
      name: 'massa quis augue',
      amount: 195.53,
      notes: 'Integer a nibh.',
      createdAt: '2023-11-22T14:05:46Z',
      categoryId: 12,
      userId: 2,
    },
    {
      name: 'pretium iaculis diam erat',
      amount: 191.33,
      notes: null,
      createdAt: '2024-04-18T01:08:45Z',
      categoryId: 10,
      userId: 2,
    },
    {
      name: 'quis libero',
      amount: 57.62,
      notes: null,
      createdAt: '2024-08-15T19:10:30Z',
      categoryId: 9,
      userId: 2,
    },
    {
      name: 'id nulla',
      amount: 80.2,
      notes: null,
      createdAt: '2024-02-09T01:38:29Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'parturient montes',
      amount: 17.35,
      notes: null,
      createdAt: '2024-07-02T00:39:43Z',
      categoryId: 12,
      userId: 2,
    },
    {
      name: 'in blandit ultrices',
      amount: 98.21,
      notes: null,
      createdAt: '2023-10-27T01:22:56Z',
      categoryId: 10,
      userId: 2,
    },
    {
      name: 'nulla ultrices aliquet maecenas leo',
      amount: 45.22,
      notes: null,
      createdAt: '2024-08-03T00:05:03Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'felis fusce posuere',
      amount: 166.56,
      notes: null,
      createdAt: '2025-02-07T10:10:05Z',
      categoryId: 10,
      userId: 2,
    },
    {
      name: 'donec odio justo sollicitudin ut',
      amount: 56.36,
      notes: null,
      createdAt: '2023-08-21T02:31:53Z',
      categoryId: 11,
      userId: 2,
    },
    {
      name: 'aliquet pulvinar',
      amount: 41.89,
      notes: null,
      createdAt: '2024-02-24T16:45:54Z',
      categoryId: 12,
      userId: 2,
    },
    {
      name: 'a odio',
      amount: 156.69,
      notes: null,
      createdAt: '2024-03-20T14:34:20Z',
      categoryId: 9,
      userId: 2,
    },
    {
      name: 'mus etiam vel',
      amount: 73.33,
      notes: null,
      createdAt: '2024-10-03T10:36:20Z',
      categoryId: 9,
      userId: 2,
    },
    {
      name: 'neque duis bibendum morbi non',
      amount: 64.66,
      notes:
        'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.',
      createdAt: '2023-05-02T07:08:01Z',
      categoryId: 9,
      userId: 2,
    },
    {
      name: 'suspendisse ornare',
      amount: 146.79,
      notes:
        'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.',
      createdAt: '2023-07-23T05:26:12Z',
      categoryId: 12,
      userId: 2,
    },
    {
      name: 'vestibulum eget vulputate',
      amount: 43.49,
      notes: 'Morbi porttitor lorem id ligula.',
      createdAt: '2023-07-29T22:25:05Z',
      categoryId: 12,
      userId: 2,
    },
    {
      name: 'at diam nam tristique',
      amount: 110.63,
      notes: null,
      createdAt: '2024-03-18T00:46:56Z',
      categoryId: 12,
      userId: 2,
    },
    {
      name: 'dictumst etiam',
      amount: 129.29,
      notes: null,
      createdAt: '2024-10-03T08:25:50Z',
      categoryId: 10,
      userId: 2,
    },
    {
      name: 'mi pede',
      amount: 52.05,
      notes: null,
      createdAt: '2023-06-17T03:11:05Z',
      categoryId: 10,
      userId: 2,
    },
    {
      name: 'duis bibendum morbi non quam',
      amount: 117.71,
      notes: null,
      createdAt: '2024-05-28T08:23:57Z',
      categoryId: 11,
      userId: 2,
    },
  ];

  await prisma.transaction.createMany({
    data: [
      ...firstUserIncomes,
      ...firstUserExpenses,
      ...secondUserIncomes,
      ...secondUserExpenses,
    ],
  });
};

const truncateTables = async () => {
  await prisma.$executeRawUnsafe(
    `TRUNCATE TABLE users, categories, transactions RESTART IDENTITY CASCADE`,
  );
};

const main = async () => {
  await truncateTables();

  await generateUsers();
  await generateCategories();
  await generateTransactions();
};

main()
  .catch((e) => console.log(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
